#!/bin/sh
set -eu

fail() {
    echo "configure-endpoint: invalid MCPASTE_ENDPOINT" >&2
    exit 1
}

endpoint=${MCPASTE_ENDPOINT-}
[ -n "$endpoint" ] || fail

case "$endpoint" in
    https://*) ;;
    *) fail ;;
esac

authority=${endpoint#https://}
[ -n "$authority" ] || fail

case "$authority" in
    */*|*\?*|*\#*|*@*|*[!A-Za-z0-9._:-]*) fail ;;
esac

case "$authority" in
    .*|*.) fail ;;
esac

output="macos/MCPaste/Sources/MCPasteCore/EndpointConfiguration.generated.swift"
directory=$(dirname "$output")
mkdir -p "$directory"
temporary=$(mktemp "$directory/.EndpointConfiguration.generated.swift.XXXXXX")
trap 'rm -f "$temporary"' EXIT HUP INT TERM

escaped=$(printf '%s' "$endpoint" | sed 's/\\/\\\\/g; s/"/\\"/g')
{
    printf '%s\n' "// Generated by scripts/configure-endpoint.sh. Do not edit or commit."
    printf '%s\n' "enum MCPasteBuildConfiguration {"
    printf '    static let endpoint = "%s"\n' "$escaped"
    printf '%s\n' "}"
} > "$temporary"
mv "$temporary" "$output"
trap - EXIT HUP INT TERM
